version: "3.7"
services:

## --------------------------- CRM APP --------------------------- ##

  crm-app:
    build: .
    image: crm-app:latest
    
    volumes:
      - crm_data:/app/data
    
    networks:
      - net_01
    
    environment:
      - NODE_ENV=production
      - PORT=5000
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.crm-app.rule=Host(`crm5x.flowmax.digital`)
        - traefik.http.routers.crm-app.entrypoints=websecure
        - traefik.http.services.crm-app.loadbalancer.server.port=5000
        - traefik.http.routers.crm-app.service=crm-app
        - traefik.http.routers.crm-app.tls.certresolver=letsencryptresolver
        - com.centurylinklabs.watchtower.enable=true

## --------------------------- CRM APP --------------------------- ##

volumes:
  crm_data:
    external: true
    name: crm_data

networks:
  net_01:
    name: net_01
    external: true